apiVersion: v1
kind: Service
metadata:
  name: backend-catalog
  namespace: backends
spec:
  selector:
    app: backend-catalog
  ports:
    - port: 8081        # <–– catalog escucha en 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-catalog
  namespace: backends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-catalog
  template:
    metadata:
      labels:
        app: backend-catalog
    spec:
      containers:
        - name: backend-catalog
          image: backend-catalog:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: DATABASE_HOST
              value: mysql.databases.svc.cluster.local
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: bookstore
            - name: DATABASE_USER
              value: user
            - name: DATABASE_PASSWORD
              value: password
