apiVersion: v1
kind: Service
metadata:
  name: backend-reviews
  namespace: backends
spec:
  selector:
    app: backend-reviews
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-reviews
  namespace: backends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-reviews
  template:
    metadata:
      labels:
        app: backend-reviews
    spec:
      containers:
        - name: backend-reviews
          image: backend-reviews:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo.databases.svc.cluster.local:27017/reviews
