apiVersion: v1
kind: Service
metadata:
  name: backend-store
  namespace: backends
spec:
  selector:
    app: backend-store
  ports:
    - port: 8082
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-store
  namespace: backends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-store
  template:
    metadata:
      labels:
        app: backend-store
    spec:
      containers:
        - name: backend-store
          image: backend-store:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: MYSQL_DB_HOST
              value: mysql.databases.svc.cluster.local
            - name: MYSQL_DB_PORT
              value: "3306"
            - name: MYSQL_DB_USERNAME
              value: user
            - name: MYSQL_DB_PASSWORD
              value: password
            - name: MYSQL_DB_NAME
              value: store
