apiVersion: v1
kind: Service
metadata:
  name: backend-store-nodeport
  namespace: backends
spec:
  type: NodePort
  selector:
    app: backend-store
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30081
